# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"
  
  # Define as informações do servidor opencms
  config.vm.define "opencms" do |opencms|
    opencms.vm.hostname = "opencms.net"
    opencms.vm.network "private_network", ip: "192.168.100.10"
    
    opencms.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
    end

    opencms.vm.provision "shell", path: "./opencms.sh"
  end

  # Define as informações do servidor de psql
  config.vm.define "psql" do |psql|
    psql.vm.network "private_network", ip: "192.168.100.20"

    psql.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end

    psql.vm.provision "shell", path: "./psql.sh"
  end

  config.vm.provision "shell", path: "./disable.sh"

end
